name: Monthly Invoice Automation

on:
  schedule:
    # Runs at 00:00 on the 2nd day of each month
    - cron: "40 14 29 * *"

jobs:
  call-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Endpoint
        run: |
          curl -X GET https://stripe-auto-1kbytdtjf-muhammad-umairs-projects-8622659f.vercel.app/api/scheduled
